### ISSUE TITLE
Agent configuration protocol crash

### ISSUE THREAD

**Issue by kryptops** [kryptops/lycanthropy#27]
Agent configuration protocol causes crash in some circumstances. This appears to be somehow triggered by a retrieval of archived authentication requests.

Server output:
```
python3 lysys.py
STARTING THREADED DNS SERVER ...
STARTING API AS SUBPROCESSES ...
BUILD SERVER IS ALREADY RUNNING
 * Serving Flask app "portal" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on https://0.0.0.0:56114/ (Press CTRL+C to quit)

<bound method objStructure.auth of <lycanthropy.daemon.messager.objStructure object at 0x7fae8dd10e10>>
{
    "error": "msgID 0swS not in message table, backing up from archive"
}

```

Agent output:

```
java -jar buildstub-0.1.jar
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at agent.Netw.send(Netw.java:77)
        at agent.Core.setup(Core.java:38)
        at agent.Main.main(Main.java:22)
Caused by: java.lang.NullPointerException
        at agent.Conf.retrieve(Conf.java:31)
        at agent.Conf.dispatch(Conf.java:87)
        ... 7 more
```

**Comment by kryptops** [comment]
Crash is caused by an authentication failure during the makeAuthSuccess call performed by conf, seemingly as a result of whatever is going wrong with the auth protocol (most likely a retransmission). Specifically, makeAuthSuccess returns a status of 1, indicating that the cookie could not be verified as deriving from the cookiedough for the agent's session. 

Possible solution: allow auth to overwrite entries in the session table when new session generated.

**Comment by kryptops** [comment]
Solution has been implemented and is being tested. Initial results suggest that the crash has been remedied.
