### ISSUE TITLE
Lycanthropy throws error on Linux when executiong Agent.Pushmod for posix module

### ISSUE THREAD

**Issue by kryptops** [kryptops/lycanthropy#30]
Ran agent.pushmod for the posix module pushing to an ubuntu instance. The following stacktrace is thrown:
```
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at agent.Proc$1.run(Proc.java:68)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at agent.Netw.send(Netw.java:77)
        at agent.Pkg.retrieve(Pkg.java:27)
        at agent.Pkg.install(Pkg.java:18)
        at agent.control.agentPushmod(control.java:131)
        ... 6 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at agent.Dist.dispatch(Dist.java:141)
        ... 14 more
```

**Comment by kryptops** [comment]
It's because the lycanthropy/etc/dist/manifest.json was missing the module ID for posix.
